# ============================================================
# Multi-stage Dockerfile for Next.js (serasa-kreatif)
# Optimized for: small image size, security, production readiness
#
# Build:  docker build -t serasa-kreatif .
# Run:    docker run -p 3000:3000 --env-file .env.local serasa-kreatif
# ============================================================

# Stage 1: Install dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files first for layer caching
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts

# ============================================================
# Stage 2: Build the application
FROM node:20-alpine AS builder
WORKDIR /app

# Reuse installed dependencies
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the Next.js app (standalone mode)
RUN npm run build

# ============================================================
# Stage 3: Production runtime image (smallest possible)
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create a non-root system user for security
# Running as root in containers is a security anti-pattern
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Copy public assets (static files, images, fonts)
COPY --from=builder /app/public ./public

# Copy the standalone Next.js server (generated by output: 'standalone')
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static files (.next/static) — CSS, JS chunks, etc.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

# Expose application port
EXPOSE 3000

# Health check — Docker will mark container as unhealthy if this fails
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health 2>/dev/null || wget -qO- http://localhost:3000 2>/dev/null || exit 1

# Start the standalone Next.js server
CMD ["node", "server.js"]
