name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        if: matrix.node-version == '18.x'

      - name: Run E2E tests
        run: npm run test:e2e
        if: matrix.node-version == '18.x'

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always() && matrix.node-version == '18.x'
        with:
          name: playwright-report-node-${{ matrix.node-version }}
          path: playwright-report/
          retention-days: 30

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
